'use client';

import { useState } from 'react';
import { Activity, ArrowUpRight, Bell, CalendarDays, Check, ChevronDown, Clock3, FileText, LayoutDashboard, MessageCircle, MoreHorizontal, Plus, Search, Settings2, Sparkles, Stethoscope, Users, Video, X } from 'lucide-react';

const appointments = [
  { time: '08:30', patient: 'Marina Azevedo', type: 'Retorno · Cardiologia', doctor: 'Dra. Helena Martins', status: 'confirmado', color: 'mint' },
  { time: '09:15', patient: 'Rafael Gomes', type: 'Primeira consulta · Ortopedia', doctor: 'Dr. Caio Nunes', status: 'aguardando', color: 'amber' },
  { time: '10:00', patient: 'Beatriz Sampaio', type: 'Avaliação · Dermatologia', doctor: 'Dra. Helena Martins', status: 'confirmado', color: 'mint' },
  { time: '11:30', patient: 'Lucas Ribeiro', type: 'Teleconsulta · Clínica geral', doctor: 'Dr. Caio Nunes', status: 'pendente', color: 'blue' },
];

const conversations = [
  { initials: 'AS', name: 'Ana Souza', text: 'Queria confirmar meu horário de amanhã...', time: 'agora', unread: true, tone: 'coral' },
  { initials: 'FM', name: 'Felipe Martins', text: 'A Dra. Helena atende convênio?', time: '8 min', unread: true, tone: 'violet' },
  { initials: 'PC', name: 'Paula Costa', text: 'Perfeito, obrigada!', time: '22 min', unread: false, tone: 'green' },
];

function StatusPill({ children, tone }: { children: React.ReactNode; tone: string }) { return <span className={`status status-${tone}`}><span className="status-dot" />{children}</span>; }

export default function Home() {
  const [section, setSection] = useState('Visão geral');
  const [showNotifications, setShowNotifications] = useState(false);
  const [checkedIn, setCheckedIn] = useState<string[]>([]);

  return <main className="shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Activity size={18} strokeWidth={2.7} /></span><span>clinic<span>flow</span></span><span className="brand-beta">AI</span></div>
      <div className="workspace-switcher"><div className="clinic-avatar">CV</div><div><strong>Clínica Vitta</strong><small>Unidade Jardins</small></div><ChevronDown size={15} /></div>
      <nav><p className="nav-label">Workspace</p>{[[LayoutDashboard, 'Visão geral'], [MessageCircle, 'Atendimento', '12'], [CalendarDays, 'Agenda'], [Users, 'Pacientes'], [FileText, 'Prontuários']].map(([Icon, label, count]: any) => <button className={section === label ? 'nav-item active' : 'nav-item'} onClick={() => setSection(label)} key={label}><Icon size={18} />{label}{count && <span className="nav-count">{count}</span>}</button>)}<p className="nav-label space-top">Gestão</p>{[[Stethoscope, 'Equipe'], [Settings2, 'Configurações']].map(([Icon, label]: any) => <button className={section === label ? 'nav-item active' : 'nav-item'} onClick={() => setSection(label)} key={label}><Icon size={18} />{label}</button>)}</nav>
      <div className="sidebar-bottom"><div className="pulse-card"><div className="pulse-icon"><Sparkles size={15} /></div><div><strong>IA em operação</strong><span>Atendimento 24/7 ativo</span></div><i /></div><div className="user-chip"><div className="avatar avatar-lime">MC</div><div><strong>Mariana Costa</strong><small>Administradora</small></div><MoreHorizontal size={17} /></div></div>
    </aside>
    <section className="content">
      <header className="topbar"><div className="crumb"><span>Workspace</span><b>/</b><strong>{section}</strong></div><div className="top-actions"><div className="search"><Search size={17} /><input placeholder="Buscar paciente, conversa..." /></div><button className="icon-button notification" onClick={() => setShowNotifications(!showNotifications)}><Bell size={19} /><span /></button>{showNotifications && <div className="notification-pop"><strong>Notificações</strong><p>3 novas mensagens aguardam resposta.</p><p>Rafael Gomes chegou à recepção.</p></div>}<div className="avatar avatar-coral">MC</div></div></header>
      <div className="main-scroll"><div className="welcome-row"><div><p className="eyebrow">QUINTA-FEIRA, 04 DE SETEMBRO DE 2026</p><h1>Bom dia, Mariana <span>✦</span></h1><p className="subheading">Aqui está o pulso da sua clínica hoje.</p></div><button className="primary-button"><Plus size={17} />Novo agendamento</button></div>
      <div className="metric-grid"><div className="metric-card accent-lime"><div className="metric-head"><span>Consultas hoje</span><CalendarDays size={18} /></div><strong>24</strong><small><em>+12%</em> vs. última quinta</small><div className="sparkline lime-line"><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="metric-card accent-coral"><div className="metric-head"><span>Conversas abertas</span><MessageCircle size={18} /></div><strong>18</strong><small><em>4 novas</em> nos últimos 30 min</small><div className="sparkline coral-line"><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="metric-card accent-blue"><div className="metric-head"><span>Tempo de resposta</span><Clock3 size={18} /></div><strong>1m 42s</strong><small><em>−28%</em> com a assistente IA</small><div className="sparkline blue-line"><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="metric-card accent-violet"><div className="metric-head"><span>Taxa de confirmação</span><Check size={18} /></div><strong>92<sup>%</sup></strong><small><em>+5%</em> nesta semana</small><div className="sparkline violet-line"><i /><i /><i /><i /><i /><i /><i /><i /></div></div></div>
      <div className="dashboard-grid"><div className="panel agenda-panel"><div className="panel-header"><div><h2>Agenda de hoje</h2><p>Quinta, 04 de setembro <span>·</span> 24 consultas</p></div><button className="ghost-button">Ver agenda completa <ArrowUpRight size={15} /></button></div><div className="agenda-list">{appointments.map((item) => <div className="appointment-row" key={item.time}><div className="appointment-time">{item.time}</div><div className={`appointment-status-line ${item.color}`} /><div className="appointment-person"><div className={`avatar avatar-${item.color}`}>{item.patient.split(' ').map((n) => n[0]).join('')}</div><div><strong>{item.patient}</strong><span>{item.type}</span></div></div><div className="appointment-doctor"><span>Profissional</span><strong>{item.doctor}</strong></div><div className="appointment-action">{item.status === 'aguardando' ? <button className="checkin-button" onClick={() => setCheckedIn((current) => [...current, item.patient])}>{checkedIn.includes(item.patient) ? <><Check size={14} /> Na sala</> : 'Check-in'}</button> : <StatusPill tone={item.color}>{item.status}</StatusPill>}<button className="dots"><MoreHorizontal size={17} /></button></div></div>)}</div></div><div className="panel inbox-panel"><div className="panel-header"><div><h2>Atendimento</h2><p>WhatsApp <span className="live-dot" /> ao vivo</p></div><button className="circle-add"><Plus size={17} /></button></div><div className="inbox-tabs"><button className="tab-active">Todas <b>18</b></button><button>Não lidas <b>4</b></button></div><div className="conversation-list">{conversations.map((conversation) => <div className="conversation" key={conversation.name}><div className={`avatar avatar-${conversation.tone}`}>{conversation.initials}</div><div className="conversation-copy"><div><strong>{conversation.name}</strong>{conversation.unread && <span className="unread-dot" />}</div><p>{conversation.text}</p></div><time>{conversation.time}</time></div>)}</div><button className="inbox-footer">Abrir central de atendimento <ArrowUpRight size={15} /></button></div></div>
      <div className="bottom-grid"><div className="panel ai-panel"><div className="ai-orb"><Sparkles size={19} /></div><div><p className="eyebrow">ASSISTENTE CLINICFLOW</p><h2>A clínica não para quando você sai.</h2><p>A IA acolheu <strong>64 conversas</strong> esta semana e converteu <strong>18 agendamentos</strong> automaticamente.</p></div><div className="ai-chart"><span style={{ height: '38%' }} /><span style={{ height: '54%' }} /><span style={{ height: '44%' }} /><span style={{ height: '78%' }} /><span style={{ height: '62%' }} /><span style={{ height: '92%' }} /></div></div><div className="panel tele-panel"><div className="tele-heading"><div className="tele-icon"><Video size={18} /></div><div><h2>Próxima teleconsulta</h2><p>Começa em 01h 18min</p></div></div><div className="tele-person"><div className="avatar avatar-blue">LR</div><div><strong>Lucas Ribeiro</strong><span>Clínica geral · 11:30</span></div><button className="ghost-button">Abrir sala <ArrowUpRight size={14} /></button></div></div></div>
      <footer><span>ClinicFlow AI · Operação clínica em um só lugar</span><a href="https://deerflow.tech" target="_blank" rel="noreferrer">Created By Deerflow</a></footer>
      </div></section>
  </main>;
}
